name: Latest dev.to post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 18 * * *' # Runs once a day at 1800 hours
  workflow_dispatch: 

jobs:
  update-with-posts:
    name: Update GH profile with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/alisaduncan"